import { useEffect, useState } from "react";
import { Link, useLocation } from "react-router-dom";
import { AnimatePresence, motion, useScroll, useSpring } from "motion/react";
import { rise, stagger } from "./motion";

export function Reveal({children,className="",delay=0}){return <motion.div className={className} variants={rise} initial="hidden" whileInView="visible" viewport={{once:true,amount:.16}} transition={{delay}}>{children}</motion.div>}
export function LightboxImage({src,alt="Project artwork",className=""}){const [open,setOpen]=useState(false);useEffect(()=>{if(!open)return;const close=e=>e.key==="Escape"&&setOpen(false);document.addEventListener("keydown",close);document.body.style.overflow="hidden";return()=>{document.removeEventListener("keydown",close);document.body.style.overflow=""}},[open]);return <><button className={`lightbox-trigger ${className}`} onClick={()=>setOpen(true)} aria-label={`Enlarge ${alt}`}><img src={src} alt={alt} loading="lazy" decoding="async"/><span>View larger ↗</span></button><AnimatePresence>{open&&<motion.div className="lightbox" initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}} onClick={()=>setOpen(false)} role="dialog" aria-modal="true" aria-label={alt}><motion.img src={src} alt={alt} initial={{scale:.92,y:20}} animate={{scale:1,y:0}} exit={{scale:.96}} transition={{duration:.45,ease:[.22,1,.36,1]}} onClick={e=>e.stopPropagation()}/><button onClick={()=>setOpen(false)} aria-label="Close enlarged image">×</button></motion.div>}</AnimatePresence></>}

export function HotspotImage({src,alt="Project artwork",className="",hotspots=[]}){const [active,setActive]=useState(null);const points=hotspots.length?hotspots:[{src,alt,x:88,y:86}];useEffect(()=>{if(!active)return;const close=e=>e.key==="Escape"&&setActive(null);document.addEventListener("keydown",close);document.body.style.overflow="hidden";return()=>{document.removeEventListener("keydown",close);document.body.style.overflow=""}},[active]);return <><div className={`hotspot-image ${className}`}><img src={src} alt={alt}/>{points.map((point,index)=><span className="hotspot-anchor" style={{left:`${point.x}%`,top:`${point.y}%`}} key={`${point.src}-${index}`}><motion.button className="hotspot-symbol" onClick={()=>setActive(point)} aria-label={`View ${point.alt||point.label||alt}`} animate={{scale:[1,1.12,1],rotate:[0,7,0]}} transition={{duration:2.2,repeat:Infinity,ease:"easeInOut",delay:index*.25}} whileHover={{scale:1.18}} whileTap={{scale:.92}}><span/><i>{hotspots.length?index+1:"+"}</i></motion.button></span>)}</div><AnimatePresence>{active&&<motion.div className="lightbox" initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}} onClick={()=>setActive(null)} role="dialog" aria-modal="true" aria-label={active.alt||active.label||alt}><motion.img src={active.src} alt={active.alt||active.label||alt} initial={{scale:.88,y:28}} animate={{scale:1,y:0}} exit={{scale:.95}} transition={{duration:.5,ease:[.22,1,.36,1]}} onClick={e=>e.stopPropagation()}/><button onClick={()=>setActive(null)} aria-label="Close enlarged image">×</button></motion.div>}</AnimatePresence></>}

export function LightboxVideo({src,alt="Project video",className=""}){const [open,setOpen]=useState(false);useEffect(()=>{if(!open)return;const close=e=>e.key==="Escape"&&setOpen(false);document.addEventListener("keydown",close);document.body.style.overflow="hidden";return()=>{document.removeEventListener("keydown",close);document.body.style.overflow=""}},[open]);return <><button className={`video-lightbox-trigger ${className}`} onClick={()=>setOpen(true)} aria-label={`Play ${alt}`}><span aria-hidden="true"/></button><AnimatePresence>{open&&<motion.div className="lightbox video-lightbox" initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}} onClick={()=>setOpen(false)} role="dialog" aria-modal="true" aria-label={alt}><motion.video src={src} controls autoPlay playsInline initial={{scale:.92,y:20}} animate={{scale:1,y:0}} exit={{scale:.96}} transition={{duration:.45,ease:[.22,1,.36,1]}} onClick={e=>e.stopPropagation()}/><button onClick={()=>setOpen(false)} aria-label="Close video">×</button></motion.div>}</AnimatePresence></>}
export function Header(){const [open,setOpen]=useState(false);const {pathname}=useLocation();useEffect(()=>{setOpen(false);window.scrollTo(0,0)},[pathname]);useEffect(()=>{document.body.style.overflow=open?"hidden":"";return()=>{document.body.style.overflow=""}},[open]);const links=[["/","Home"],["/about","About"],["/project","Projects"],["/contact","Contact"]];return <><header className="site-header shell"><Link className="brand" to="/"><span className="brand-mark">A</span><span className="brand-name">ATELIER<em>studio</em></span></Link><button className={`menu-toggle ${open?"is-open":""}`} aria-label={open?"Close menu":"Open menu"} aria-expanded={open} onClick={()=>setOpen(!open)}><span/><span/></button><Link className="button button-light header-cta" to="/contact">Start project</Link></header><AnimatePresence>{open&&<><motion.button className="nav-backdrop" aria-label="Close menu" initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}} transition={{duration:.5,ease:"easeOut"}} onClick={()=>setOpen(false)}/><motion.nav className="site-nav" aria-label="Primary navigation" initial={{x:"100%"}} animate={{x:0}} exit={{x:"100%"}} transition={{duration:.82,ease:[.76,0,.24,1]}}><motion.button className="nav-close" onClick={()=>setOpen(false)} aria-label="Close menu" initial={{opacity:0,rotate:-30}} animate={{opacity:1,rotate:0}} exit={{opacity:0,rotate:20}} transition={{delay:.35,duration:.45}}><span/><span/></motion.button><div className="nav-links">{links.map(([to,label],i)=><motion.div key={to} initial={{opacity:0,x:55}} animate={{opacity:1,x:0}} exit={{opacity:0,x:25}} transition={{delay:.24+i*.075,duration:.62,ease:[.22,1,.36,1]}}><Link className={pathname===to?"active":""} to={to}><span>0{i+1}</span>{label}</Link></motion.div>)}</div><motion.div className="nav-meta" initial={{opacity:0,y:15}} animate={{opacity:1,y:0}} exit={{opacity:0}} transition={{delay:.65,duration:.5}}><p>Independent creative studio</p><a href="mailto:erismendoza21@gmail.com">erismendoza21@gmail.com</a></motion.div></motion.nav></>}</AnimatePresence></>}
const footerOffers=[
  ["Sick of an outdated brand?","I’ve got you.","Brand Identity"],
  ["Need visuals that communicate?","I can make it clear.","Graphic Design"],
  ["Social posts getting ignored?","Let’s make them stop the scroll.","Social Media Design"],
  ["Need your story captured?","I’ll frame it with purpose.","Photography"],
  ["Footage needs more energy?","I’ll shape the rhythm.","Video Editing"],
  ["Want your graphics to move?","Let’s bring them to life.","Motion Graphics"],
  ["Need a stronger digital home?","I’ll build it clearly.","Web Development"]
];
function FooterOfferPopout(){const [step,setStep]=useState(0);const phase=step%3;const offer=footerOffers[Math.floor(step/3)%footerOffers.length];useEffect(()=>{const phaseDurations=[3600,3200,5200];const timer=window.setTimeout(()=>setStep(value=>(value+1)%(footerOffers.length*3)),phaseDurations[phase]);return()=>window.clearTimeout(timer)},[step,phase]);const questionWords=offer[0].split(" ");const serviceWords=offer[2].split(" ");const cumulativeWidths=serviceWords.map((_,index)=>Math.min(500,Math.max(118,serviceWords.slice(0,index+1).join(" ").length*13+46)));const finalWidth=Math.min(560,cumulativeWidths.at(-1)+48);const widthFrames=[...cumulativeWidths,finalWidth];const widthTimes=widthFrames.map((_,index)=>index/(widthFrames.length-1||1));const checkDelay=.25+serviceWords.length*.78;return <div className="footer-offer" aria-live="polite" aria-atomic="true"><div className="footer-offer-stage"><AnimatePresence mode="wait">{phase<2?<motion.div key={`${offer[2]}-${phase}`} className={`footer-offer-copy phase-${phase}`} initial={{opacity:0,y:18,scale:.98}} animate={{opacity:1,y:0,scale:1}} exit={{opacity:0,y:-12,scale:.96}} transition={{duration:.8,ease:[.22,1,.36,1]}}>{phase===0&&questionWords.map((word,index)=><motion.span key={`${word}-${index}`} initial={{opacity:0,y:16,filter:"blur(5px)"}} animate={{opacity:1,y:0,filter:"blur(0px)"}} transition={{delay:index*.12,duration:.65,ease:[.22,1,.36,1]}}>{word}</motion.span>)}{phase===1&&<motion.span className="footer-offer-answer">{offer[1]}</motion.span>}</motion.div>:<motion.div key={`${offer[2]}-result`} className="footer-offer-pill" initial={{opacity:0,width:cumulativeWidths[0]}} animate={{opacity:1,width:widthFrames}} exit={{opacity:0,y:-10}} transition={{width:{duration:checkDelay+.55,times:widthTimes,ease:[.22,1,.36,1]},opacity:{duration:.35}}}><motion.span className="footer-offer-mark" initial={{rotate:-45,scale:.3,opacity:0}} animate={{rotate:0,scale:1,opacity:1}} transition={{delay:checkDelay,type:"spring",stiffness:300,damping:18}}>✓</motion.span><motion.span className="footer-offer-result" aria-label={offer[2]} animate={{x:[0,0,20]}} transition={{duration:checkDelay+.55,times:[0,checkDelay/(checkDelay+.55),1],ease:[.22,1,.36,1]}}>{serviceWords.map((word,index)=><motion.span className="footer-offer-word" aria-hidden="true" key={`${word}-${index}`} initial={{opacity:0,y:"115%",filter:"blur(3px)"}} animate={{opacity:1,y:"0%",filter:"blur(0px)"}} transition={{delay:.2+index*.78,duration:.62,ease:[.22,1,.36,1]}}>{word}</motion.span>)}</motion.span></motion.div>}</AnimatePresence></div></div>}
export function Footer(){return <><section className="contact section-pad"><Reveal className="shell contact-inner"><p className="serif-label">CREATIVE © 2026</p><h2>Ready to make<br/><i>something</i></h2><div className="contact-action"><p>Have a creative project in mind? I’d love to help turn your ideas into clear, meaningful visuals.</p><Link className="button button-red" to="/contact">Start a project</Link></div></Reveal></section><footer className="site-footer shell"><div className="footer-brand"><span>ATELIER</span><em>Designed to feel</em></div><div><a href="tel:+971566330668">+971 56 633 0668</a><a href="mailto:erismendoza21@gmail.com">erismendoza21@gmail.com</a></div><div><Link to="/">Home</Link><Link to="/about">About</Link><Link to="/project">Projects</Link><Link to="/contact">Contact</Link></div><div><p>Follow what we’re building.</p><form className="subscribe-form" onSubmit={e=>e.preventDefault()}><input type="email" placeholder="Email address"/><button>↗</button></form><Link to="/legal-pages/privacy-policy">Privacy Policy</Link></div><div className="footer-wordmark">ATELIER <i>studio</i></div></footer></>}
function BackToTop(){const [visible,setVisible]=useState(false);useEffect(()=>{const update=()=>setVisible(window.scrollY>500);update();window.addEventListener("scroll",update,{passive:true});return()=>window.removeEventListener("scroll",update)},[]);return <button className={`back-to-top ${visible?"is-visible":""}`} type="button" aria-label="Back to top" onClick={()=>window.scrollTo({top:0,behavior:"smooth"})}>↑</button>}
export function Layout({children}){const {scrollYProgress}=useScroll();const scaleX=useSpring(scrollYProgress,{stiffness:120,damping:30});return <><motion.div className="progress" style={{scaleX}}/><Header/><main>{children}</main><Footer/><BackToTop/></>}
export function PageHero({kicker,title,script,copy,className=""}){return <motion.section className={`page-hero shell ${className}`.trim()} variants={stagger} initial="hidden" animate="visible">{kicker&&<motion.p variants={rise} className="eyebrow">{kicker}</motion.p>}<div className="clip"><motion.h1 initial={{y:"110%"}} animate={{y:0}} transition={{duration:1.05,ease:[.22,1,.36,1]}}>{title} {script&&<i>{script}</i>}</motion.h1></div>{copy&&<motion.p variants={rise} className="page-lead">{copy}</motion.p>}</motion.section>}
