import { motion, useScroll, useTransform } from "motion/react";
import { useState } from "react";
import { Link, useParams, useSearchParams } from "react-router-dom";
import { LightboxImage, Reveal, PageHero } from "./components";
import { useContent } from "./content";
import { posts, projects, projectTypes, team } from "./data";
import { mask, rise, stagger } from "./motion";

const shuffledProjectSlugs=projects.map(project=>project.slug);
for(let index=shuffledProjectSlugs.length-1;index>0;index--){const swapIndex=Math.floor(Math.random()*(index+1));[shuffledProjectSlugs[index],shuffledProjectSlugs[swapIndex]]=[shuffledProjectSlugs[swapIndex],shuffledProjectSlugs[index]]}
const shuffledProjectOrder=new Map(shuffledProjectSlugs.map((slug,index)=>[slug,index]));const greenCoverProjectSlugs=new Set(["in-out-concepts-2024","web-development-showcase","web-development-demo","kabayan-cargo-social-media","airlink-collateral-design","collateral-demo","airlink-international-uae","leisure-solutions","airlink-international-motion-graphic","airlink-photoshoots-2025","dubai-airshow-2025"]);function alternateProjectCoverTones(projectList){const beigeProjects=projectList.filter(project=>!greenCoverProjectSlugs.has(project.slug));const greenProjects=projectList.filter(project=>greenCoverProjectSlugs.has(project.slug));const alternatingProjects=[];while(beigeProjects.length||greenProjects.length){if(beigeProjects.length)alternatingProjects.push(beigeProjects.shift());if(greenProjects.length)alternatingProjects.push(greenProjects.shift());}return alternatingProjects}
const homeSelectedProjectTypes=["Brand Identity","Social Media","Photography & Photo Editing","Motion Graphics","Collateral Design"];
const photographyHoverCovers={"gulfood-2025":"gulfood.jpg","dubai-airshow-2025":"dubai-airshow.jpg","dubai-boat-show-2025":"dubai-boat-show.jpg","dubai-autodrome-24h-series-2025":"dubai-autodrome-24h.jpg","airlink-photoshoots-2025":"airlink-photoshoots.jpg"};
const privacySections=[
  {title:"Introduction",paragraphs:["This Privacy Policy explains how Eris Portfolio collects, uses, stores, and protects personal information when you visit this website, contact me about a project, or interact with links and features provided through the site."]},
  {title:"Information you provide",paragraphs:["You may provide personal information when you contact me by email or through any contact method made available on this website. This may include your name, email address, phone number, company or organization, project details, and any other information you choose to include in your message."]},
  {title:"Technical information",paragraphs:["The website and its hosting provider may automatically process limited technical information needed to deliver and secure the site, such as your IP address, browser and device type, operating system, referring page, requested pages, and access time. I do not use this information to identify you personally unless required for security or legal reasons."]},
  {title:"How your information is used",paragraphs:["Personal information may be used to respond to enquiries, discuss potential projects, provide requested services, maintain correspondence, improve website performance and accessibility, prevent misuse, protect the website, and comply with applicable legal obligations."],items:["Respond to messages and project enquiries","Prepare proposals or provide requested information","Maintain the security and reliability of the website","Improve the content and user experience","Meet legal, regulatory, or contractual requirements"]},
  {title:"Cookies and similar technologies",paragraphs:["This portfolio does not intentionally use advertising cookies or behavioral-tracking cookies. The hosting platform or embedded third-party services may use essential technologies required for security, media delivery, or basic operation. If analytics or additional cookie-based services are introduced, this policy will be updated accordingly."]},
  {title:"Sharing your information",paragraphs:["I do not sell or rent personal information. Information may be shared only with service providers that support website hosting, email, storage, or project delivery; when required by law or a valid legal request; or when necessary to protect rights, safety, and website security. Service providers are expected to handle information only for the relevant service." ]},
  {title:"Third-party links and platforms",paragraphs:["The website includes links and QR codes that may open third-party websites or social platforms. Those services operate under their own privacy policies and practices. I am not responsible for how external websites collect or use information after you leave this portfolio."]},
  {title:"Data retention",paragraphs:["Personal information is kept only for as long as reasonably necessary to respond to an enquiry, manage a professional relationship, maintain appropriate business records, resolve disputes, or meet legal obligations. Information that is no longer needed will be deleted or securely anonymized where practical."]},
  {title:"Data security",paragraphs:["Reasonable administrative and technical measures are used to protect personal information against unauthorized access, loss, misuse, alteration, or disclosure. No internet transmission or electronic storage system can be guaranteed to be completely secure, so absolute security cannot be promised."]},
  {title:"Your privacy rights",paragraphs:["Depending on the laws that apply to you, you may have rights to request access to your personal information, correct inaccurate information, request deletion, restrict or object to certain processing, withdraw consent, or request a copy of information you provided. A request may require reasonable identity verification before it can be completed." ]},
  {title:"International data processing",paragraphs:["Website hosting, email, and other service providers may process information in countries outside your place of residence. Where this occurs, reasonable steps are taken to use reputable providers and appropriate protections for the information involved."]},
  {title:"Children's privacy",paragraphs:["This portfolio is intended for a general professional audience and is not directed to children. I do not knowingly collect personal information from children. If you believe a child has provided personal information through this website, please contact me so it can be reviewed and removed where appropriate."]},
  {title:"Changes to this policy",paragraphs:["This Privacy Policy may be updated when website features, service providers, or legal requirements change. The latest version will be posted on this page with a revised last-updated date."]}
];

function SectionTitle({script,title}){return <Reveal className="section-heading"><p className="script">{script}</p><h2>{title}</h2></Reveal>}
function ProjectCard({project,index=0}){const [showPhoto,setShowPhoto]=useState(false);const tags=project.tags?.length?project.tags:[project.category];const hoverCover=photographyHoverCovers[project.slug];const hoverImage=hoverCover?`${import.meta.env.BASE_URL}assets/photography/hover-covers/${hoverCover}`:null;return <motion.article className={`project-card ${project.size||""} ${hoverImage?"project-card-photo-fade":""}`} variants={rise} initial="hidden" whileInView="visible" viewport={{once:true,amount:.1}} layout><Link to={`/project/${project.slug}`}><motion.div className="project-image" whileHover="hover" onPointerEnter={()=>hoverImage&&setShowPhoto(true)} onPointerLeave={()=>setShowPhoto(false)}>{hoverImage?<img className="project-cover-default" style={{opacity:showPhoto?0:1}} src={project.image} alt={`${project.title} project artwork`}/>:<motion.img variants={{hover:{scale:1.045}}} transition={{duration:.8}} src={project.image} alt={`${project.title} project artwork`}/>} {hoverImage&&<img className="project-cover-hover" style={{opacity:showPhoto?1:0}} src={hoverImage} alt="" aria-hidden="true"/>}<span>{String(index+1).padStart(2,"0")}</span><motion.b initial={{scale:0}} whileHover={{scale:1}}>↗</motion.b></motion.div><div className="project-meta"><h3>{project.title}</h3><p>{project.category}</p><time>{project.year}</time></div><div className="project-tags" aria-label="Project types">{tags.map(tag=><span key={tag}>{tag}</span>)}</div></Link></motion.article>}
function PostCard({post,featured=false}){return <motion.article className={`post-card ${featured?"featured":""}`} variants={rise} initial="hidden" whileInView="visible" viewport={{once:true,amount:.12}}><Link to={`/blog/${post.slug}`}><div className="post-image"><motion.img whileHover={{scale:1.04}} transition={{duration:.7}} src={post.image} alt="Placeholder editorial artwork"/></div><p>{post.category}</p><h2>{post.title}</h2><time>{post.date}</time></Link></motion.article>}

export function Home(){const {clients,projects,services,processSteps,testimonials}=useContent();const selectedProjects=homeSelectedProjectTypes.map(type=>projects.find(project=>project.tags?.includes(type))).filter(Boolean);return <>
  <motion.section className="hero shell" variants={stagger} initial="hidden" animate="visible"><h1>{["CURATED","BOLD","AMBITION"].map((line,i)=><span className="hero-line clip" key={line}><motion.b variants={mask}>{line}{i===0&&<em>for</em>}</motion.b></span>)}</h1><motion.div variants={rise} className="hero-aside"><p className="serif-label">DESIGN THAT<br/>EARNS ATTENTION.</p><p>We do fewer projects, so each one gets everything we have.</p><div className="hero-stats"><div><strong>40+</strong><span>Projects</span></div><div><strong>5+</strong><span>Years</span></div><motion.div className="orbit" animate={{rotate:360}} transition={{duration:18,repeat:Infinity,ease:"linear"}}>✦</motion.div></div><p className="capabilities">BRAND IDENTITY <b>·</b> WEB DESIGN <b>·</b> CAMPAIGNS</p></motion.div></motion.section>
  <section className="media-break"><motion.img initial={{scale:1.12}} whileInView={{scale:1}} viewport={{once:true}} transition={{duration:1.5,ease:[.22,1,.36,1]}} src="assets/placeholder-05.svg" alt="Cinematic placeholder artwork"/><Reveal className="media-caption"><span>Built to move people</span><p>Guide attention, create feeling, leave a mark.</p></Reveal></section>
  <section className="statement section-pad shell"><Reveal><p className="eyebrow">Built to move people, guide attention, and leave a mark.</p><div className="statement-grid"><div className="statement-art"><span>DIGITAL</span><motion.span initial={{x:-70}} whileInView={{x:0}} transition={{duration:1}}>FIRST</motion.span><small>Est. 2020<br/>Remote-first<br/>Worldwide</small></div><div className="statement-media"><motion.img initial={{rotate:-8,scale:.86}} whileInView={{rotate:0,scale:1}} viewport={{once:true}} transition={{duration:1.1,ease:[.22,1,.36,1]}} src="assets/placeholder-02.svg" alt="Abstract placeholder artwork"/><span>✦ Independent creative practice</span></div><div className="statement-copy"><h2>CREATIVE<br/>STUDIO</h2><p>A focused digital studio building brands, interfaces, and stories that earn attention.</p><p>We partner with founders and teams to shape ideas into polished digital products.</p></div></div></Reveal></section>
  <Reveal className="client-strip shell"><span>Clients we worked with</span><div className="client-list">{clients.map(x=><span key={x}>{x}</span>)}</div></Reveal>
  <section className="home-work section-pad shell"><SectionTitle script="Creative studio" title="Selected work"/><div className="home-work-layout"><div className="home-project-list">{selectedProjects.map((p,i)=><Reveal className="home-project-row" key={p.slug}><span>{String(i+1).padStart(2,"0")}</span><Link to={`/project/${p.slug}`}><strong>{p.title}</strong><small>{p.category}</small></Link><time>{p.year}</time></Reveal>)}<Link className="button button-red" to="/project">View all projects</Link></div><div className="home-work-mosaic">{selectedProjects.map((p,i)=><Reveal className={`mosaic-image mosaic-${i+1}`} key={p.slug}><Link to={`/project/${p.slug}`}><img src={p.image} alt="Project placeholder"/><span>{p.title}</span></Link></Reveal>)}</div></div></section>
  <section className="services section-pad shell"><Reveal className="services-intro"><div><p className="eyebrow">Creative services</p><h2>What we make,<br/><i>and why it matters.</i></h2></div><div><p>Every engagement begins with deep listening and ends with work that outlasts the brief — online and off.</p><Link className="button button-dark" to="/contact">Begin a project</Link></div></Reveal><div className="services-grid">{services.map(([n,t,c])=><Reveal className="service-card" key={n}><span>s{n}</span><div><p>{c}</p><h3>{t}</h3></div><b>↗</b></Reveal>)}</div></section>
  <section className="process section-pad shell"><SectionTitle script="Thoughtful process" title="How we work"/><div className="process-list">{processSteps.map(([t,c],i)=><Reveal className="process-row" key={t}><span>step {String(i+1).padStart(2,"0")}</span><h3>{t}</h3><p>{c}</p><b>↘</b></Reveal>)}</div></section>
  <section className="bento shell"><Reveal className="bento-main"><p>What makes us different</p><h2>CRAFT<br/><i>over</i> CLUTTER</h2><div className="pills"><span>Typography</span><span>Motion</span><span>Rhythm</span><span>Structure</span></div></Reveal><Reveal className="bento-note"><span>✦</span><h3>Shape what comes next</h3><p>Focused work with deliberate visual rhythm and systems built to scale.</p></Reveal><Reveal className="bento-stat"><strong>40+</strong><span>Projects delivered</span><a href="mailto:erismendoza21@gmail.com">erismendoza21@gmail.com</a></Reveal><Reveal className="bento-art"><img src="assets/placeholder-03.svg" alt="Placeholder portrait artwork"/></Reveal></section>
  <section className="testimonials section-pad shell"><SectionTitle script="Words from clients" title="Kind notes"/><div className="testimonial-mosaic">{testimonials.concat(testimonials.slice(0,2)).map(([q,n,r],i)=><Reveal className={`testimonial-note note-${i+1}`} key={`${n}-${i}`}><img src={`assets/placeholder-0${i%5+1}.svg`} alt="Client placeholder"/><div><blockquote>“{q}”</blockquote><figcaption><strong>{n}</strong><span>{r}</span></figcaption></div></Reveal>)}</div></section>
  </>}

export function About(){return <><PageHero kicker="Est. 2020" title="About the" script="studio" copy="A contemporary creative practice focused on typography, structure, and immersive digital experiences."/><section className="about-intro shell section-pad"><Reveal><p>We create modern portfolio systems, visual identities, and editorial-inspired digital experiences for brands, agencies, and creative teams.</p><p>Our approach combines structured layouts, immersive storytelling, typography, and motion to build presentation systems that feel clean, intentional, and memorable.</p></Reveal></section><section className="numbers shell">{[["40+","Selected Projects"],["06","Years Building"],["Global","Remote Collaborations"],["12","Creative Industries"]].map(x=><Reveal className="number" key={x[1]}><strong>{x[0]}</strong><span>{x[1]}</span></Reveal>)}</section><section className="team section-pad shell"><SectionTitle script="Our team" title="Small by design"/><div className="team-grid">{team.map((p,i)=><Reveal className="team-card" key={p.name}><div className="team-image"><motion.img whileHover={{scale:1.04}} src={p.image} alt="Team placeholder"/></div><h3>{p.name}</h3><p>{p.role}</p><span>0{i+1}</span></Reveal>)}</div></section><section className="awards section-pad shell"><SectionTitle script="Featured and" title="recognitions"/><div>{["Awwwards — Honorable Mention — 2022","CSS Design Awards — Website of the Day — 2023","Behance — Featured Gallery — 2024","Framer Marketplace — Featured Template — 2025","Independent Design Awards — Digital Experience — 2026"].map((x,i)=><Reveal className="award-row" key={x}><span>Award 0{i+1}</span><h3>{x}</h3><b>↗</b></Reveal>)}</div></section><section className="latest section-pad shell"><SectionTitle script="Latest" title="from the journal"/><div className="posts-grid">{posts.slice(0,4).map(p=><PostCard key={p.slug} post={p}/>)}</div></section></>}

export function Projects(){const {projects:contentProjects}=useContent();const [searchParams,setSearchParams]=useSearchParams();const requestedType=searchParams.get("type");const activeType=projectTypes.includes(requestedType)?requestedType:"All";const orderedProjects=[...contentProjects].sort((a,b)=>(shuffledProjectOrder.get(a.slug)??Number.MAX_SAFE_INTEGER)-(shuffledProjectOrder.get(b.slug)??Number.MAX_SAFE_INTEGER));const matchingProjects=activeType==="All"?orderedProjects:orderedProjects.filter(project=>project.tags?.includes(activeType));const filteredProjects=alternateProjectCoverTones(matchingProjects);const selectType=type=>{const next=new URLSearchParams(searchParams);if(type==="All")next.delete("type");else next.set("type",type);setSearchParams(next,{replace:true});};return <><PageHero className="projects-hero" title="Projects driven" script="by visions"/><section className="project-index shell section-pad"><div className="project-filter" aria-label="Filter projects by type"><div className="project-filter-heading"><span>Explore by discipline</span></div><div className="project-filter-controls">{["All",...projectTypes].map(type=><button key={type} type="button" className={activeType===type?"active":""} aria-pressed={activeType===type} onClick={()=>selectType(type)}>{type}</button>)}</div></div>{filteredProjects.length?<motion.div className="projects-grid" layout>{filteredProjects.map((project,index)=><ProjectCard project={project} index={index} key={project.slug}/>)}</motion.div>:<motion.div className="project-empty" initial={{opacity:0,y:20}} animate={{opacity:1,y:0}}><span>Coming soon</span><h2>No {activeType.toLowerCase()} projects have been added yet.</h2><p>This category is ready for your next portfolio entry. Add the matching tag to a project in the content data or future CMS and it will appear here automatically.</p></motion.div>}</section><section className="studio-marquee"><motion.div initial={{x:"8%"}} whileInView={{x:"-8%"}} transition={{duration:1.5,ease:[.22,1,.36,1]}}>ATELIER <i>studio</i></motion.div></section></>}

export function ProjectDetail(){const {slug}=useParams();const project=projects.find(p=>p.slug===slug)||projects[0];return <><section className="detail-hero shell"><motion.p initial={{opacity:0}} animate={{opacity:1}}>{project.category} · {project.year}</motion.p><div className="clip"><motion.h1 variants={mask} initial="hidden" animate="visible">{project.title}</motion.h1></div><a className="text-link" href="#overview">View live site ↗</a></section><Reveal className="detail-cover"><img src={project.image} alt="Project placeholder"/></Reveal><section id="overview" className="case-study shell section-pad"><Reveal className="case-meta"><span>Category: {project.category}</span><span>Client: Your Client</span><span>Year: {project.year}</span><span>Location: Worldwide</span></Reveal><Reveal className="case-copy"><h2>Project Overview</h2><p>{project.title} tasked us with transforming an ambitious idea into a trusted, intuitive experience that could build confidence, improve engagement, and establish a memorable visual position.</p><h2>Our Approach</h2><p>We began with a focused audit, mapping the complete journey and identifying the moments where design could add clarity, trust, and personality.</p><ul><li>Clearer onboarding and navigation.</li><li>A scalable visual system for rapid growth.</li><li>Thoughtful motion that guides attention.</li></ul></Reveal><div className="case-gallery"><Reveal><img src={`${import.meta.env.BASE_URL}assets/placeholder-02.svg`} alt="Project placeholder"/></Reveal><Reveal><img src={`${import.meta.env.BASE_URL}assets/placeholder-04.svg`} alt="Project placeholder"/></Reveal></div><Reveal className="results"><div><strong>35%</strong><span>Increase in sign-ups</span></div><div><strong>22%</strong><span>Boost in daily users</span></div><div><strong>3x</strong><span>Faster navigation</span></div></Reveal><Reveal className="case-quote">“The design feels considered, approachable, and effortless.”<span>— Your Client, Product Director</span></Reveal></section><section className="other-work shell section-pad"><SectionTitle script="Other" title="Works"/><div className="projects-grid">{projects.filter(p=>p.slug!==project.slug).slice(0,3).map((p,i)=><ProjectCard key={p.slug} project={p} index={i}/>)}</div></section></>}

export function ProjectDetailLightbox(){
  const {slug}=useParams();
  const project=projects.find(p=>p.slug===slug)||projects[0];
  return <>
    <section className="detail-hero shell"><motion.p initial={{opacity:0}} animate={{opacity:1}}>{project.category} · {project.year}</motion.p><div className="clip"><motion.h1 variants={mask} initial="hidden" animate="visible">{project.title}</motion.h1></div><a className="text-link" href="#overview">Explore project ↓</a></section>
    <Reveal className="detail-cover shell"><LightboxImage src={project.image} alt={`${project.title} cover placeholder`}/></Reveal>
    <section id="overview" className="case-study shell section-pad">
      <Reveal className="case-meta"><span>Category: {project.category}</span><span>Client: Your Client</span><span>Year: {project.year}</span><span>Location: Worldwide</span></Reveal>
      <Reveal className="case-copy"><h2>Project Overview</h2><p>{project.title} tasked us with transforming an ambitious idea into a trusted, intuitive experience that could build confidence, improve engagement, and establish a memorable visual position.</p><h2>Our Approach</h2><p>We began with a focused audit, mapping the complete journey and identifying the moments where design could add clarity, trust, and personality.</p><ul><li>Clearer onboarding and navigation.</li><li>A scalable visual system for rapid growth.</li><li>Thoughtful motion that guides attention.</li></ul></Reveal>
      <div className="case-gallery"><Reveal><LightboxImage src="assets/placeholder-02.svg" alt={`${project.title} gallery placeholder one`}/></Reveal><Reveal><LightboxImage src="assets/placeholder-04.svg" alt={`${project.title} gallery placeholder two`}/></Reveal></div>
      <Reveal className="results"><div><strong>35%</strong><span>Increase in sign-ups</span></div><div><strong>22%</strong><span>Boost in daily users</span></div><div><strong>3x</strong><span>Faster navigation</span></div></Reveal>
      <Reveal className="case-quote">“The design feels considered, approachable, and effortless.”<span>— Your Client, Product Director</span></Reveal>
    </section>
    <section className="other-work shell section-pad"><SectionTitle script="Other" title="Works"/><div className="projects-grid">{projects.filter(p=>p.slug!==project.slug).slice(0,3).map((p,i)=><ProjectCard key={p.slug} project={p} index={i}/>)}</div></section>
  </>
}

export function Contact(){return <><PageHero kicker="Start a conversation" title="Get in" script="touch"/><section className="contact-page shell section-pad"><Reveal className="contact-details">{[["Email","erismendoza21@gmail.com"],["Phone","+971 56 633 0668"],["Location","Deira, Dubai UAE"]].map(x=><div key={x[0]}><span>{x[0]}</span><a href="#form">{x[1]}</a></div>)}</Reveal><Reveal className="contact-form-wrap"><div><h2>Let’s make it happen</h2><p>Whether you’re building a portfolio, launching a brand, or exploring a new digital direction, we’d love to hear about your project and creative vision.</p></div><form id="form" className="contact-form" onSubmit={e=>e.preventDefault()}><label>Full name*<input required/></label><label>Email address*<input type="email" required/></label><label>Phone number<input type="tel"/></label><label>Project type<select><option>Brand identity</option><option>Website</option><option>Creative direction</option></select></label><label className="full">Message<textarea rows="5"/></label><button className="button button-dark">Send message</button></form></Reveal></section></>}

export function Privacy(){return <><PageHero kicker="Last updated: August 16, 2026" title="Privacy" script="Policy"/><article className="legal shell section-pad">{privacySections.map(section=><Reveal key={section.title}><h2>{section.title}</h2>{section.paragraphs.map(paragraph=><p key={paragraph}>{paragraph}</p>)}{section.items&&<ul>{section.items.map(item=><li key={item}>{item}</li>)}</ul>}</Reveal>)}<Reveal><h2>Contact</h2><p>For privacy questions or requests concerning your personal information, email <a href="mailto:erismendoza21@gmail.com">erismendoza21@gmail.com</a>.</p></Reveal></article></>}
export function NotFound(){return <section className="not-found shell"><motion.p animate={{rotate:[0,5,-5,0]}} transition={{duration:2,repeat:Infinity}}>404</motion.p><h1>Lost in the studio?</h1><Link className="button button-dark" to="/">Return home</Link></section>}
