import { AnimatePresence, motion } from "motion/react";
import { useEffect, useRef, useState } from "react";
import { Link, useParams } from "react-router-dom";
import { HotspotImage, LightboxImage, LightboxVideo, Reveal } from "./components";
import { projects } from "./data";
import { mask, rise } from "./motion";

const disciplineOrder=["Social Media","Motion Graphics","Videography & Video Editing","Photography & Photo Editing","Web Development","Brand Identity","Collateral Design"];
const disciplineClass={"Social Media":"social","Motion Graphics":"motion","Videography & Video Editing":"video","Photography & Photo Editing":"photo","Web Development":"web","Brand Identity":"brand","Collateral Design":"collateral"};
const toolIcons={
  "Photoshop":"photoshop.svg",
  "Illustrator":"illustrator.svg",
  "Canva":"canva.svg",
  "Blender":"blender.svg",
  "CapCut":"capcut.svg",
  "Premiere Pro":"premiere-pro.svg",
  "Lightroom":"lightroom.svg",
  "After Effects":"after-effects.svg"
};
const disciplineTools={
  "Brand Identity":["Photoshop","Illustrator"],
  "Social Media":["Photoshop","Illustrator","Canva","CapCut","Premiere Pro"],
  "Photography & Photo Editing":["Photoshop","Lightroom"],
  "Collateral Design":["Photoshop","Illustrator"],
  "Videography & Video Editing":["Premiere Pro","After Effects","CapCut"],
  "Motion Graphics":["After Effects","Blender"]
};

function projectDiscipline(project){return disciplineOrder.find(tag=>project.tags?.includes(tag))||"Collateral Design"}
function projectMedia(project){return [project.image,...(project.gallery||[])]}
function projectPrimaryVideo(project){
  return project.detailVideo || project.fullVideo || project.mainVideo || project.motionVideo || project.showcaseVideo || project.videoUrl || project.videoSrc || project.videoFile || project.videoMp4 || project.video;
}

function ProjectTools({discipline}){const tools=disciplineTools[discipline];if(!tools)return null;return <Reveal className="project-tools"><div className="project-tools-heading"><span>TOOLS USED</span><h2>Creative toolkit</h2></div><div className="project-tools-list">{tools.map(tool=><div className="project-tool" key={tool}><img src={`${import.meta.env.BASE_URL}assets/software/${toolIcons[tool]}`} alt="" aria-hidden="true"/><span>{tool}</span></div>)}</div></Reveal>}

function SocialProjectLink({project}){const links={"kabayan-cargo-social-media":{name:"Kabayan Cargo",href:"https://www.facebook.com/AirlinkKabayanCargoOfficial",qr:"assets/social/kabayan-cargo/facebook-qr.svg",platform:"Facebook"},"philippine-travel-services":{name:"Philippine Travel Services",href:"https://www.facebook.com/AirlinkPHTravel",qr:"assets/social/philippine-travel-services/facebook-qr.svg",platform:"Facebook"},"airlink-international-uae":{name:"Airlink International UAE",href:"https://www.linkedin.com/company/airlinkuae",qr:"assets/social/airlink-international-uae/linkedin-qr.svg",platform:"LinkedIn"}};const config=links[project.slug]||{name:"Airlink Travel",href:"https://www.facebook.com/airlinkaue",qr:"assets/social/airlink-travel/facebook-qr.svg",platform:"Facebook"};return <a className="social-project-link" href={config.href} target="_blank" rel="noreferrer" aria-label={`Visit ${config.name} on ${config.platform}`}><img src={`${import.meta.env.BASE_URL}${config.qr}`} alt={`QR code for ${config.name} on ${config.platform}`}/></a>}
function YoutubeProjectLink(){return <a className="social-project-link" href="https://www.youtube.com/@airlinkinternationaluae" target="_blank" rel="noreferrer" aria-label="Visit Airlink International UAE on YouTube"><img src={`${import.meta.env.BASE_URL}assets/video/airlink-youtube/youtube-qr.svg`} alt="QR code for Airlink International UAE on YouTube"/></a>}

function SocialShowcase({project}){const media=projectMedia(project);const posts=project.posts?.length?project.posts:[...media,...media].slice(0,6).map(src=>({src,label:"Promotional post"}));const vertical=[...media.slice(1),media[0]];const reels=project.reels?.length?project.reels:vertical.slice(0,3);const stories=project.stories?.length?project.stories:vertical.slice(0,3);return <section className="discipline-showcase social-showcase"><div className="social-profile"><span className="social-avatar">ER</span><div><strong>{project.client}</strong><small>@selectedwork · Campaign showcase</small></div><b>•••</b></div><div className="social-format-heading"><span>01</span><div><h2>Feed Posts</h2><p>Square and carousel-ready campaign graphics shown as a cohesive profile grid.</p></div></div><div className="social-feed">{posts.map((post,index)=>{const src=typeof post==="string"?post:post.src;const label=typeof post==="string"?"Promotional post":post.label;return <Reveal className={`social-post social-post-${index+1}`} key={`${src}-${index}`}><LightboxImage src={src} alt={`${project.title} ${label.toLowerCase()} ${index+1}`}/><div><span>♡　◇　↗</span><small>{label} · {String(index+1).padStart(2,"0")}</small></div></Reveal>})}</div><div className="social-format-heading"><span>02</span><div><h2>Reels</h2><p>Vertical reel covers and motion-first previews presented inside a mobile video interface.</p></div></div><div className="social-phone-row social-reels">{reels.map((src,index)=><Reveal className="social-phone" key={`reel-${src}`}><div className="phone-shell"><div className="phone-island"/><div className="phone-screen"><video src={src} muted loop autoPlay playsInline preload="metadata" aria-label={`${project.title} reel preview ${index+1}`}/><LightboxVideo className="reel-expand" src={src} alt={`${project.title} reel ${index+1}`}/><div className="reel-actions"><span>♡</span><span>◇</span><span>↗</span></div><div className="reel-caption"><strong>@selectedwork</strong><small>Reel cover · 0{index+1}</small></div></div></div></Reveal>)}</div><div className="social-format-heading"><span>03</span><div><h2>Stories / My Day</h2><p>Full-screen, time-sensitive designs with story progress, profile, and call-to-action placement.</p></div></div><div className="social-phone-row social-stories">{stories.map((src,index)=><Reveal className="social-phone" key={`story-${src}`}><div className="phone-shell"><div className="phone-island"/><div className="phone-screen"><img src={src} alt={`${project.title} story preview ${index+1}`}/><div className="story-progress"><i/><i/><i/></div><div className="story-profile"><span>ER</span><strong>selectedwork</strong><small>2h</small></div><button>Learn more　⌃</button><LightboxImage className="phone-expand" src={src} alt={`${project.title} story preview ${index+1}`}/></div></div></Reveal>)}</div></section>}

function CargoSocialShowcase({project}){return <section className="discipline-showcase social-showcase cargo-social-showcase"><div className="social-profile"><span className="social-avatar">KC</span><div><strong>{project.client}</strong><small>Campaign content · Dubai, UAE</small></div><b>•••</b></div><div className="social-format-heading"><span>01</span><div><h2>Campaign Posts</h2><p>Promotional, service, and customer-focused graphics presented as one cohesive social media collection.</p></div></div><div className="social-feed">{project.posts.map((post,index)=><Reveal className={`social-post social-post-${index+1}`} key={post.src}><LightboxImage src={post.src} alt={`${project.title} ${post.label.toLowerCase()}`}/><div><span>♡　◇　↗</span><small>{post.label} · {String(index+1).padStart(2,"0")}</small></div></Reveal>)}</div><div className="social-format-heading"><span>02</span><div><h2>Reels</h2><p>Short-form cargo operations, loading updates, and service-focused edits produced for Kabayan Cargo.</p></div></div><div className="social-phone-row social-reels">{project.reels.map((src,index)=><Reveal className="social-phone" key={src}><div className="phone-shell"><div className="phone-island"/><div className="phone-screen"><video src={src} muted loop autoPlay playsInline preload="metadata" aria-label={`${project.title} reel preview ${index+1}`}/><LightboxVideo className="reel-expand" src={src} alt={`${project.title} reel ${index+1}`}/><div className="reel-actions"><span>♡</span><span>◇</span><span>↗</span></div><div className="reel-caption"><strong>Kabayan Cargo</strong><small>Cargo reel · {String(index+1).padStart(2,"0")}</small></div></div></div></Reveal>)}</div></section>}

function PhilippineSocialShowcase({project}){return <section className="discipline-showcase social-showcase philippine-social-showcase"><div className="social-profile"><span className="social-avatar">PH</span><div><strong>{project.client}</strong><small>Travel content · Dubai, UAE</small></div><b>•••</b></div><div className="social-format-heading"><span>01</span><div><h2>Feed Posts</h2><p>Travel advertising, engagement content, destination features, and branded daily inspiration.</p></div></div><div className="social-feed">{project.posts.map((post,index)=><Reveal className={`social-post social-post-${index+1}`} key={post.src}><LightboxImage src={post.src} alt={`${project.title} ${post.label.toLowerCase()}`}/><div><span>♡　◇　↗</span><small>{post.label} · {String(index+1).padStart(2,"0")}</small></div></Reveal>)}</div><div className="social-format-heading"><span>02</span><div><h2>Reels</h2><p>Short-form travel campaigns edited for Philippine Travel Services.</p></div></div><div className="social-phone-row social-reels">{project.reels.map((src,index)=><Reveal className="social-phone" key={src}><div className="phone-shell"><div className="phone-island"/><div className="phone-screen"><video src={src} muted loop autoPlay playsInline preload="metadata" aria-label={`${project.title} reel preview ${index+1}`}/><LightboxVideo className="reel-expand" src={src} alt={`${project.title} reel ${index+1}`}/><div className="reel-actions"><span>♡</span><span>◇</span><span>↗</span></div><div className="reel-caption"><strong>Philippine Travel Services</strong><small>Travel reel · {String(index+1).padStart(2,"0")}</small></div></div></div></Reveal>)}</div></section>}
function InternationalSocialShowcase({project}){return <section className="discipline-showcase social-showcase"><div className="social-profile"><span className="social-avatar">AI</span><div><strong>{project.client}</strong><small>LinkedIn content · Dubai, UAE</small></div><b>•••</b></div><div className="social-format-heading"><span>01</span><div><h2>LinkedIn Feed</h2><p>Corporate logistics communication, service campaigns, company updates, and industry-focused content designed for a professional audience.</p></div></div><div className="social-feed">{project.posts.map((post,index)=><Reveal className={`social-post social-post-${index+1}`} key={post.src}><LightboxImage src={post.src} alt={`${project.title} ${post.label.toLowerCase()}`}/><div><span>♡　◇　↗</span><small>{post.label} · {String(index+1).padStart(2,"0")}</small></div></Reveal>)}</div><div className="social-format-heading"><span>02</span><div><h2>Event Reels</h2><p>Short-form event coverage and behind-the-scenes edits produced for Airlink International UAE.</p></div></div><div className="social-phone-row social-reels">{project.reels.map((reel,index)=><Reveal className="social-phone" delay={index*100} key={reel.src}><div className="phone-shell"><div className="phone-island"/><div className="phone-screen"><video src={reel.src} muted loop autoPlay playsInline preload="metadata" aria-label={`${project.title} ${reel.label}`}/><LightboxVideo className="reel-expand" src={reel.src} alt={`${project.title} ${reel.label}`}/><div className="reel-actions"><span>♡</span><span>◇</span><span>↗</span></div><div className="reel-caption"><strong>Airlink International UAE</strong><small>{reel.label}</small></div></div></div></Reveal>)}</div></section>}

function MotionShowcase({project}){const media=projectMedia(project);const mainVideo=projectPrimaryVideo(project);return <section className="discipline-showcase motion-showcase"><div className="motion-screen motion-video"><video src={mainVideo} controls autoPlay muted playsInline preload="auto" aria-label={`${project.title} video`}/></div>{project.slug!=="airlink-international-motion-graphic"&&<div className="motion-project-note"><span>MAIN MOTION PIECE</span><p>Play the finished animation above. The native timeline now shows the actual duration, playback position, volume, and fullscreen controls.</p></div>}<div className="motion-frames">{media.slice(1).map((src,index)=>{const isVideo=/\.(mp4|webm|mov)(\?.*)?$/i.test(src);const label=project.slug==="circus-music-fest-2024"?(index===0?"01 / BLENDER PROCESS":"02 / LIVE EVENT RESULT"):`${String(index+1).padStart(2,"0")} / OTHER MOTION GRAPHIC`;return <Reveal key={`${src}-${index}`}><div className="motion-gif">{isVideo?<video src={src} controls muted playsInline preload="metadata" aria-label={`${project.title} motion graphic ${index+1}`}/>:<img src={src} alt={`${project.title} motion graphic ${index+1}`}/>}</div><span>{label}</span></Reveal>})}</div></section>}

function VideoShowcase({project}){const media=projectMedia(project);const detailVideo=projectPrimaryVideo(project);return <section className="discipline-showcase video-showcase"><div className="video-viewport">{detailVideo?<video src={detailVideo} poster={project.image} controls playsInline preload="metadata" aria-label={`${project.title} video`}/>:<><img src={media[0]} alt={`${project.title} video cover`}/><button aria-label="Play project video">▶</button><div className="video-controls"><span>▶　0:00 / 1:24</span><i/><span>⚙　□</span></div></>}</div><div className="video-info"><div><h2>{project.title}</h2><p>{project.overview}</p></div><span>PROJECT FILM · {project.year}</span></div><div className="video-thumbnails">{media.slice(1).map((src,index)=><Reveal key={src}><LightboxImage src={src} alt={`${project.title} video thumbnail ${index+1}`}/><strong>Chapter {index+1}</strong></Reveal>)}</div></section>}

function PublishedVideoShowcase({project}){const playlist=project.videos||[];const [active,setActive]=useState(0);const player=useRef(null);const selected=playlist[active];useEffect(()=>{if(!player.current||!selected)return;player.current.load();player.current.play().catch(()=>{})},[active,selected]);return <section className="discipline-showcase video-showcase published-video"><div className="published-video-topbar"><div><span className="published-video-mark">ER</span><strong>ERIS / VIDEO</strong></div><span>PUBLISHED PROJECTS</span></div><div className="video-viewport published-video-player">{selected?<video ref={player} src={selected.src} poster={selected.poster||project.image} controls playsInline preload="metadata" aria-label={selected.title}/>:<img src={project.image} alt={`${project.title} placeholder cover`}/>}</div><div className="video-info published-video-info"><div><span className="published-status">PUBLIC · FEATURED VIDEO</span><h2>{selected?.title||project.title}</h2><p>{selected?.description||project.overview}</p><div className="published-channel"><span>ER</span><div><strong>Eris R. Mendoza</strong><small>Creative Graphic Designer · Dubai, UAE</small></div><button type="button">VIEW PROJECT</button></div></div><aside><strong>{String(active+1).padStart(2,"0")} / {String(playlist.length).padStart(2,"0")}</strong><span>{project.year}</span></aside></div><div className="published-playlist-heading"><div><span>UP NEXT</span><h3>More video projects</h3></div><p>Select a project to play it in the featured viewport.</p></div><div className="video-thumbnails published-video-list">{playlist.map((item,index)=><motion.button type="button" className={index===active?"is-active":""} onClick={()=>setActive(index)} key={`${item.src}-${index}`} whileHover={{y:-5}} whileTap={{scale:.98}} aria-label={`Play ${item.title}`}><div><img src={item.poster||project.image} alt={`${item.title} thumbnail`}/><span>▶</span><small>{item.duration||"PLAY"}</small></div><strong>{item.title}</strong><p>{item.category||"Video editing · Published project"}</p></motion.button>)}</div></section>}

function CustomVideoPlayer({item,fallback}){const video=useRef(null);const frame=useRef(null);const [playing,setPlaying]=useState(false);const [current,setCurrent]=useState(0);const [duration,setDuration]=useState(0);const [volume,setVolume]=useState(1);const [muted,setMuted]=useState(true);useEffect(()=>{setPlaying(false);setCurrent(0);setMuted(true);if(!video.current)return;video.current.load();video.current.muted=true;video.current.play().catch(()=>{})},[item?.src]);const format=value=>{if(!Number.isFinite(value))return"0:00";const minutes=Math.floor(value/60);const seconds=Math.floor(value%60);return`${minutes}:${String(seconds).padStart(2,"0")}`};const togglePlay=()=>{if(!video.current)return;if(video.current.paused)video.current.play();else video.current.pause()};const seek=event=>{const next=Number(event.target.value);video.current.currentTime=next;setCurrent(next)};const changeVolume=event=>{const next=Number(event.target.value);setVolume(next);setMuted(next===0);video.current.volume=next;video.current.muted=next===0};const toggleMute=()=>{const next=!muted;setMuted(next);if(video.current)video.current.muted=next};const fullscreen=()=>document.fullscreenElement?document.exitFullscreen?.():frame.current?.requestFullscreen?.();return <div ref={frame} className="video-viewport published-video-player custom-video-player">{item?<video ref={video} src={item.src} poster={item.poster||fallback} autoPlay muted playsInline preload="metadata" aria-label={item.title} onClick={togglePlay} onPlay={()=>setPlaying(true)} onPause={()=>setPlaying(false)} onTimeUpdate={event=>setCurrent(event.currentTarget.currentTime)} onLoadedMetadata={event=>setDuration(event.currentTarget.duration)} onEnded={()=>setPlaying(false)}/>:<img src={fallback} alt="Video placeholder cover"/>}<div className="custom-player-bar"><input className="custom-player-progress" type="range" min="0" max={duration||0} step="0.05" value={Math.min(current,duration||0)} onChange={seek} aria-label="Video progress"/><div className="custom-player-actions"><button type="button" onClick={togglePlay} aria-label={playing?"Pause video":"Play video"}>{playing?"Ⅱ":"▶"}</button><button type="button" onClick={toggleMute} aria-label={muted?"Unmute video":"Mute video"}>{muted||volume===0?"🔇":"🔊"}</button><input className="custom-player-volume" type="range" min="0" max="1" step="0.05" value={muted?0:volume} onChange={changeVolume} aria-label="Video volume"/><span>{format(current)} / {format(duration)}</span><button className="custom-player-fullscreen" type="button" onClick={fullscreen} aria-label="Toggle fullscreen">⛶</button></div></div></div>}

function VideoPlatformShowcase({project}){const playlist=project.videos||[];const [active,setActive]=useState(0);const selected=playlist[active];return <section className="discipline-showcase video-showcase published-video youtube-feel"><header className="published-video-topbar"><div><span className="published-video-mark">ER</span><strong>ERIS VIDEO</strong></div><label><span>⌕</span> Search published projects</label><span>PORTFOLIO CHANNEL</span></header><div className="youtube-layout"><main className="youtube-watch"><CustomVideoPlayer item={selected} fallback={project.image}/><h2>{selected?.title||project.title}</h2><div className="youtube-meta-row"><span>{project.year} · Featured portfolio film</span><div><button>♡ LIKE</button><button>↗ SHARE</button><button>•••</button></div></div><div className="published-channel youtube-channel"><span>ER</span><div><strong>Eris R. Mendoza</strong><small>Creative Graphic Designer · Dubai, UAE</small></div><button type="button">VIEW PORTFOLIO</button></div><div className="youtube-description"><strong>{project.year} · {project.client}</strong><p>{selected?.description||project.overview}</p><span>{selected?.category||"Videography · Video editing · Creative direction"}</span></div></main><aside className="youtube-up-next"><div className="youtube-list-heading"><strong>Up next</strong><span>AUTOPLAY　○</span></div>{playlist.map((item,index)=><motion.button type="button" className={index===active?"is-active":""} onClick={()=>setActive(index)} key={`${item.src}-${index}`} whileHover={{x:4}} whileTap={{scale:.985}} aria-label={`Play ${item.title}`}><div className="youtube-thumb"><img src={item.poster||project.image} alt={`${item.title} thumbnail`}/><span>▶</span><small>{item.duration||"PLAY"}</small></div><div><strong>{item.title}</strong><p>Eris R. Mendoza</p><small>{item.category||"Video editing · Published project"}</small></div></motion.button>)}</aside></div></section>}

function PhotoShowcase({project}){const media=project.detailGalleryOnly?(project.gallery||[]):projectMedia(project);return <section className="discipline-showcase photo-showcase"><Reveal className="photo-gallery-heading"><div><span>SELECTED PHOTOGRAPHY</span><h2>Through the lens</h2></div><p>A curated gallery of event, corporate, lifestyle, and documentary photographs. Select any frame to view the complete image.</p></Reveal><div className="photo-gallery-grid">{media.map((src,index)=><Reveal className={`photo-gallery-item photo-gallery-item-${index+1}`} key={src}><LightboxImage src={src} alt={`${project.title} photograph ${index+1}`}/><div className="photo-gallery-caption"><span>{String(index+1).padStart(2,"0")}</span><strong>{index===0?"Featured photograph":"Selected frame"}</strong><small>{project.location}</small></div></Reveal>)}</div></section>}

function WebShowcase({project}){const media=project.detailGalleryOnly?(project.gallery||[]):projectMedia(project);return <section className="discipline-showcase web-showcase"><div className="browser-frame"><header><i/><i/><i/><span>https://your-project.com</span></header><LightboxImage src={media[0]} alt={`${project.title} desktop website`}/></div><div className="device-row">{media.slice(1).map((src,index)=><Reveal className={index?"web-mobile":"web-tablet"} key={src}><img src={src} alt={`${project.title} responsive website ${index+1}`}/></Reveal>)}</div></section>}

function BrandShowcase({project}){const slides=project.gallery||[];const labels=["Identity introduction","Core initial concept","Combined LS construction","Clear space and minimum size","Approved colour usage","Brand typography","Logo usage rules","Physical signage and vehicle application","Uniforms and corporate stationery","Social media kit"];return <section className="discipline-showcase brand-case-showcase"><Reveal className="brand-case-intro"><span>BRAND GUIDELINES · 01–10</span><h2>A visual system designed for consistency at every scale.</h2><p>The guideline sequence below moves from the thinking behind the mark into practical rules and real-world applications. Select any page to inspect it in the image viewer.</p></Reveal><div className="brand-guideline-grid">{slides.map((src,index)=><Reveal className={`brand-guideline-slide brand-guideline-slide-${index+1}`} key={src}><div className="brand-guideline-label"><span>{String(index+1).padStart(2,"0")}</span><strong>{labels[index]||"Brand application"}</strong></div><LightboxImage src={src} alt={`${project.title}: ${labels[index]||`guideline ${index+1}`}`}/></Reveal>)}</div></section>}

function CollateralCarousel({items,title="Collateral Collection"}){const [active,setActive]=useState(0);const [expanded,setExpanded]=useState(null);const total=items.length;const move=direction=>setActive(index=>(index+direction+total)%total);const offsetFor=index=>{let offset=(index-active+total)%total;if(offset>total/2)offset-=total;return offset};useEffect(()=>{if(!expanded)return;const close=event=>event.key==="Escape"&&setExpanded(null);document.addEventListener("keydown",close);document.body.style.overflow="hidden";return()=>{document.removeEventListener("keydown",close);document.body.style.overflow=""}},[expanded]);return <><Reveal className="collateral-carousel"><div className="collateral-piece-meta"><span>02</span><small>{title}</small></div><div className="collateral-carousel-stage">{items.map((item,index)=>{const offset=offsetFor(index);return <motion.button className={`collateral-slide ${offset===0?"is-active":"is-side"}`} key={item.src} initial={false} animate={{opacity:offset===0?1:.5,scale:offset===0?1:.82,x:`calc(${offset} * clamp(190px, 25vw, 430px))`,zIndex:offset===0?3:2-Math.abs(offset)}} transition={{x:{type:"spring",stiffness:82,damping:20,mass:1.05},scale:{duration:.85,ease:[.22,1,.36,1]},opacity:{duration:.7,ease:"easeOut"},zIndex:{delay:offset===0?.22:0}}} onClick={()=>offset===0?setExpanded(item):setActive(index)} aria-label={offset===0?`Enlarge ${item.alt}`:`Show ${item.alt}`}><img src={item.src} alt={item.alt}/>{offset===0&&<span className="collateral-expand-label">View closer ↗</span>}</motion.button>})}<button className="collateral-carousel-arrow is-prev" onClick={()=>move(-1)} aria-label="Previous collateral">‹</button><button className="collateral-carousel-arrow is-next" onClick={()=>move(1)} aria-label="Next collateral">›</button></div><motion.div className="collateral-carousel-caption" key={active} initial={{opacity:0,y:8}} animate={{opacity:1,y:0}} transition={{duration:.55,ease:[.22,1,.36,1]}}><strong>{items[active].alt}</strong><span>{String(active+1).padStart(2,"0")} / {String(total).padStart(2,"0")}</span></motion.div></Reveal><AnimatePresence>{expanded&&<motion.div className="lightbox collateral-lightbox" initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}} onClick={()=>setExpanded(null)} role="dialog" aria-modal="true" aria-label={expanded.alt}><motion.img src={expanded.src} alt={expanded.alt} initial={{scale:.88,y:28}} animate={{scale:1,y:0}} exit={{scale:.95}} transition={{duration:.5,ease:[.22,1,.36,1]}} onClick={event=>event.stopPropagation()}/><button onClick={()=>setExpanded(null)} aria-label="Close enlarged image">×</button></motion.div>}</AnimatePresence></>}

function CollateralShowcase({project}){if(project.hotspots?.length){const applications=[{image:project.showcaseImage||project.image,hotspots:project.hotspots,alt:`${project.title} exhibition scene`},...(project.additionalApplications||[])];return <section className="discipline-showcase collateral-showcase"><Reveal className="collateral-piece collateral-interactive"><div className="collateral-piece-meta"><span>01</span><small>INTERACTIVE COLLATERAL APPLICATIONS</small></div>{applications.map((application,index)=><div className="collateral-interactive-item" key={application.image}><HotspotImage src={application.image} alt={application.alt||`${project.title} application ${index+1}`} hotspots={application.hotspots}/>{index<applications.length-1&&<p>CONTINUE TO THE NEXT INTERACTIVE APPLICATION BELOW.</p>}</div>)}<p>SELECT A NUMBERED SYMBOL TO EXPLORE EACH COLLATERAL APPLICATION.</p></Reveal>{project.collateralCollection?.length>0&&<CollateralCarousel items={project.collateralCollection} title="Other Collateral Designs"/>}</section>}return <section className="discipline-showcase collateral-showcase">{projectMedia(project).map((src,index)=><Reveal className={`collateral-piece collateral-piece-${index+1}`} key={src}><div className="collateral-piece-meta"><span>{String(index+1).padStart(2,"0")}</span><small>PRINT / APPLICATION</small></div><HotspotImage src={src} alt={`${project.title} collateral ${index+1}`}/><p>SELECT THE ANIMATED SYMBOL TO VIEW THE FULL ARTWORK.</p></Reveal>)}</section>}

function DisciplineShowcase({project,discipline}){if(project.slug==="kabayan-cargo-social-media")return <CargoSocialShowcase project={project}/>;if(project.slug==="philippine-travel-services")return <PhilippineSocialShowcase project={project}/>;if(project.slug==="airlink-international-uae")return <InternationalSocialShowcase project={project}/>;if(discipline==="Social Media")return <SocialShowcase project={project}/>;if(discipline==="Motion Graphics")return <MotionShowcase project={project}/>;if(discipline==="Videography & Video Editing")return <VideoPlatformShowcase project={project}/>;if(discipline==="Photography & Photo Editing")return <PhotoShowcase project={project}/>;if(discipline==="Web Development")return <WebShowcase project={project}/>;if(discipline==="Brand Identity")return <BrandShowcase project={project}/>;return <CollateralShowcase project={project}/>} 

function RelatedProject({project}){return <motion.article className="project-card" variants={rise} initial="hidden" whileInView="visible" viewport={{once:true,amount:.1}}><Link to={`/project/${project.slug}`}><div className="project-image"><img src={project.image} alt={`${project.title} project artwork`}/></div><div className="project-meta"><h3>{project.title}</h3><p>{project.category}</p><time>{project.year}</time></div></Link></motion.article>}

export default function PortfolioDetail(){const {slug}=useParams();const project=projects.find(item=>item.slug===slug)||projects[0];const discipline=projectDiscipline(project);return <>
  <main className={`discipline-detail discipline-${disciplineClass[discipline]}`}>
    <section className="detail-hero shell"><motion.p initial={{opacity:0}} animate={{opacity:1}}>{discipline} · {project.year}</motion.p><div className="clip"><motion.h1 variants={mask} initial="hidden" animate="visible">{project.title}</motion.h1></div></section>
    <section id="overview" className="case-study shell section-pad"><Reveal className="case-meta"><span>Discipline: {discipline}</span><span>Client: {project.client}</span><span>Year: {project.year}</span><span>Location: {project.location}</span></Reveal><Reveal className="case-copy">{discipline==="Social Media"&&<SocialProjectLink project={project}/>} {project.slug==="airlink-youtube"&&<YoutubeProjectLink/>}<h2>Project Overview</h2><p>{project.overview}</p><h2>The Challenge &amp; Role</h2><p>{project.challenge}</p></Reveal><ProjectTools discipline={discipline}/><DisciplineShowcase project={project} discipline={discipline}/></section>
  </main>
  <section className="other-work shell section-pad"><div className="section-heading"><p className="script">Other</p><h2>Works</h2></div><div className="projects-grid">{projects.filter(item=>item.slug!==project.slug).slice(0,3).map(item=><RelatedProject key={item.slug} project={item}/>)}</div></section>
</>}
